lazy val root = (project in file("."))
  .settings(Settings.publishSettings: _*)
  .settings(name := "faunadb-jvm-parent")
  .settings(Settings.rootSettings)
  .aggregate(common, scala, java)

lazy val common = project.in(file("faunadb-common"))
  .settings(Settings.publishSettings: _*)
  .settings(name := "faunadb-common")
  .settings(Settings.faunadbCommonSettings)
  .settings(libraryDependencies ++= Dependencies.faunadbCommon)


lazy val scala = project.in(file("faunadb-scala"))
  .dependsOn(common)
  .settings(Settings.publishSettings : _*)
  .settings(name := "faunadb-scala")
  .settings(Settings.faunadbScalaSettings)
  .settings(libraryDependencies ++= Dependencies.faunadbScala)

lazy val java = project.in(file("faunadb-java"))
  .dependsOn(common)
  .settings(Settings.publishSettings: _*)
  .settings(name := "faunadb-java")
  .settings(Settings.faunadbJavaSettings)
  .settings(libraryDependencies ++= Dependencies.faunadbJava)
