# Take in a runtime image to use for the base system
# Expects a Debian-based image
ARG RUNTIME_IMAGE

# Use the docker image provided via build arg
FROM $RUNTIME_IMAGE

# Install the libraries we need for sbt and dockerize
RUN apt-get update && apt-get install -y curl bc make && rm -rf /var/lib/apt/lists/*

# Copy in the dockerize utility
ARG DOCKERIZE_VERSION=0.6.0
RUN curl -sL https://github.com/jwilder/dockerize/releases/download/v$DOCKERIZE_VERSION/dockerize-linux-amd64-v$DOCKERIZE_VERSION.tar.gz | tar -xzC /usr/local/bin

# Copy in the sbt utility
ARG SBT_VERSION=1.1.0
RUN curl -sL https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz | tar -xzC /usr/local --strip-components=1

# Copy project into the image
COPY . /fauna/faunadb-jvm

# Shift over to the project
WORKDIR /fauna/faunadb-jvm

# Define the default variables for the tests
ENV FAUNA_ROOT_KEY=secret FAUNA_DOMAIN=db.fauna.com FAUNA_SCHEME=https FAUNA_PORT=443 FAUNA_TIMEOUT=30s

# Run the tests (after target database is up)
CMD ["make", "docker-wait", "test"]
