version: 2.1
description: FaunaDB JVM Driver Tests

executors:
  core:
    parameters:
      version:
        type: enum
        enum: ["nightly"]
    resource_class: large
    docker:
      - image: openjdk:11
      - image: gcr.io/faunadb-cloud/faunadb/core/nightly:latest
        name: core
        auth:
          username: _json_key
          password: $GCR_KEY
    environment:
      SBT_VERSION: 1.4.7
      FAUNA_ROOT_KEY: secret
      FAUNA_DOMAIN: core
      FAUNA_SCHEME: http
      FAUNA_PORT: 8443
      FAUNA_TIMEOUT: 60s

commands:
  build_and_test:
    description: "Run JVM tests"
    steps:
      - run:
          name: Get sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://repo.scala-sbt.org/scalasbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb

      - checkout

      - restore_cache:
          key: faunadb-jvm-v1-{{ .Branch }}-{{checksum "project/Dependencies.scala" }}

      - run:
          name: Compile 2.11
          command: sbt ++2.11.12 compileAll

      - run:
          name: Compile 2.12
          command: sbt ++2.12.14 compileAll

      - save_cache:
          key: faunadb-jvm-v1-{{ .Branch }}-{{checksum "project/Dependencies.scala" }}
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

      - run:
          name: Test 2.11
          command: sbt ++2.11.12 test

      - run:
          name: Test 2.12
          command: sbt ++2.12.14 coverage test coverageReport

      - run:
          name: Load Test 2.11
          command: sbt ++2.11.12 load:test

      - run:
          name: Load Test 2.12
          command: sbt ++2.12.14 load:test

      - run:
          when: always
          name: Gather results
          command: |
            # TODO: save results for 2.11 as well (DRV-222).
            mkdir -p results/{tests,coverage}
            cp **/target/test-reports/*.xml results/tests/
            cp -r faunadb-scala/target/scala-2.12/*coverage-report/ results/coverage/

      - run:
          name: Generate API documentation 2.11
          command: sbt clean ++2.11.12 doc

      - run:
          name: Generate API documentation 2.12
          command: sbt clean ++2.12.14 doc

      - store_test_results:
          path: results/

jobs:
  core-nightly:
    executor:
      name: core
      version: nightly
    steps:
      - build_and_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - core-nightly:
          context: faunadb-drivers
