version: 2.1
description: FaunaDB JVM Driver Tests

executors:
  core:
    parameters:
      version:
        type: enum
        enum: ["nightly"]
    resource_class: large
    docker:
      - image: openjdk:11
    environment:
      SBT_VERSION: 1.4.7

commands:
  build_and_test:
    description: "Run JVM tests"
    steps:
      - run:
          name: Get sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://repo.scala-sbt.org/scalasbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb

      - checkout

      - restore_cache:
          key: faunadb-jvm-v1-{{ .Branch }}-{{checksum "project/Dependencies.scala" }}

      - run:
          name: Compile 2.11
          command: sbt ++2.11.12 compileAll

      - run:
          name: Compile 2.12
          command: sbt ++2.12.14 compileAll

      - store_test_results:
          path: results/

jobs:
  core-nightly:
    executor:
      name: core
      version: nightly
    steps:
      - build_and_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - core-nightly:
          context: faunadb-drivers
