---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: devex-oracle-java-11
    tag: latest
    aws_access_key_id: ((aws_access_key_id))
    aws_secret_access_key: ((aws_secret_access_key))
    aws_region: us-east-2

params:
  FAUNA_ROOT_KEY:
  FAUNA_DOMAIN:
  FAUNA_SCHEME:
  FAUNA_PORT:

inputs:
  - name: fauna-jvm-repository

run:
  path: entrypoint.sh
  args:
    - bash
    - -ceu
    - |
      # start containers
      docker-compose -f fauna-jvm-repository/concourse/tasks/integration.yml run tests-oracle-jdk-11-scala-2.11
      # stop and remove containers
      docker-compose -f fauna-jvm-repository/concourse/tasks/integration.yml down
      # remove volumes
      docker volume rm $(docker volume ls -q)
