---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: mozilla/sbt
    tag: 11.0.8_1.3.13

params:
  SONATYPE_USER:
  SONATYPE_PASS:
  GPG_PRIVATE_KEY:
  GPG_PUBLIC_KEY:
  GPG_PASSPHRASE:
  GPG_SIGNING_KEY:

inputs:
  - name: fauna-jvm-repository

outputs:
  - name: slack-message

run:
  path: ./fauna-jvm-repository/concourse/scripts/publish.sh
